[settings]
always_keep_download = false
always_keep_install = false

plugin_autoupdate_last_check_duration = '1 week'

verbose = false
http_timeout = "30s"
jobs = 4
raw = false
yes = false

not_found_auto_install = true
task_output = "prefix"
paranoid = false

trusted_config_paths = [
  '~/workspace',
]
