[window]
padding = { x = 0, y = 0 }
decorations = "Full"
startup_mode = "Windowed"
title = "Alacritty"

[font]
normal = { family = "BerkeleyMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 11.25

[scrolling]
history = 10000
multiplier = 3

[colors]
primary = { background = "#181818", foreground = "#d8d8d8" }

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"
