[language-server.expert]
command = "/usr/local/bin/expert"

[[language]]
name = "elixir"
language-servers = ["expert"]

[[language]]
name = "heex"
language-servers = ["expert"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "lsp-ai"]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "ts" ] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "lsp-ai"]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "js" ] }
auto-format = true

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "json" ] }
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]
formatter = { command = "prettier", args = [ "--parser", "html" ] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
formatter = { command = "prettier", args = [ "--parser", "css" ] }
auto-format = true
